In [1]:
%matplotlib inline
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
image1 = np.zeros((10,10))

In [4]:
image1[6,1]=1
image1[6,2]=1
image1[6,3]=1
image1[6,4]=1
image1[3,7]=1
image1[4,7]=1
image1[5,7]=1
image1[6,7]=1

print(image1)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
filter11 = np.hstack((np.zeros((4,1)),np.ones((4,2)),np.zeros((4,1))))
print(filter11)




[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]]


In [6]:
from scipy import signal
grad = signal.convolve2d(image1, filter11, boundary='symm', mode='same')
print(grad)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 3. 0.]
 [0. 1. 2. 2. 2. 1. 0. 4. 4. 0.]
 [0. 1. 2. 2. 2. 1. 0. 3. 3. 0.]
 [0. 1. 2. 2. 2. 1. 0. 2. 2. 0.]
 [0. 1. 2. 2. 2. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
import skimage.measure
print(skimage.measure.block_reduce(grad, (2,2), np.max))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 2.]
 [1. 2. 2. 4. 4.]
 [1. 2. 2. 3. 3.]
 [1. 2. 2. 1. 1.]]


In [8]:
filter12 = np.vstack((np.zeros((1,4)),np.ones((2,4)),np.zeros((1,4))))
print(filter12)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


In [10]:
grad = signal.convolve2d(image1, filter12, boundary='symm', mode='same')
print(grad)
print(skimage.measure.block_reduce(grad, (2,2), np.max))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 2. 2. 2. 2.]
 [2. 2. 3. 4. 3. 2. 3. 2. 2. 2.]
 [2. 2. 3. 4. 3. 2. 2. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 2. 2.]
 [2. 4. 3. 3. 2.]
 [0. 0. 0. 0. 0.]]
